# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='\u8d44\u8baf\u6807\u9898', max_length=100)),
                ('category', models.TextField(default='\u884c\u4e1a\u52a8\u6001')),
                ('source', models.TextField(default='H-ui')),
                ('update_time', models.TextField(default='2017-8-6')),
                ('see_times', models.TextField(default='1111')),
                ('publish_status', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
