# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
